version: "3"
services:
  flask:
    build: .
    
    #command: flask run --host=0.0.0.0
    command: gunicorn -w 1 -b 0.0.0.0:5000 hello:app --reload
    environment:
        - FLASK_APP=hello.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=TRUE
    ports:
        - '5000:5000'
    volumes:
        - ./:/mnt/test/flask
